FROM cytopia/php-fpm-7.1
ARG USER_ID=1000
MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>
ENV DEBIAN_FRONTEND noninteractive

RUN yum install php-memcached -y

RUN usermod -u $USER_ID apache

WORKDIR /var/www/laravel

ADD ./laravel.ini /etc/php-custom.d
ADD ./xdebug.ini /etc/php-custom.d
# ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/

# CMD ["php-fpm"]

EXPOSE 9000
