FROM php:7.1-fpm
ARG USER_ID=1000
MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

ADD ./laravel.ini /usr/local/etc/php/conf.d
ADD ./xdebug.ini /usr/local/etc/php/conf.d
ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libmemcached-dev \
    curl \
    libjpeg-dev \
    libpng12-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev \
    libxml2-dev \
    libicu-dev \
    gettext \
    locales-all \
    git \
    --no-install-recommends

# install mcrypt library
RUN docker-php-ext-install mcrypt

# Install mongodb driver
RUN pecl install mongodb

# configure gd library
RUN docker-php-ext-configure gd \
    --enable-gd-native-ttf \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2

# Install xdebug
RUN pecl install xdebug && \
    docker-php-ext-enable xdebug

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install  -j$(nproc) \
    pdo_mysql \
    pdo_pgsql \
    gd \
    gettext \
    intl

# Install Memcached for php 7

RUN git clone --branch php7 https://github.com/php-memcached-dev/php-memcached /usr/src/php/ext/memcached \
  && cd /usr/src/php/ext/ \
  && ( \
        cd memcached \
        && phpize \
        && ./configure \
        && make -j$(nproc) \
        && make install \
    ) \
    && rm -r memcached \
    && docker-php-ext-enable memcached

RUN usermod -u $USER_ID www-data

RUN apt-get purge git -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/laravel

CMD ["php-fpm"]

EXPOSE 9000
