#service to run: nginx postgres mailcatcher memcached bind redis ldap-admin

version: '2'

services:

### Nginx Server Container ##################################

    nginx:
        build: 
            context: ./nginx
            args:
                - USER_ID=${EUID}
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### PHP-FPM Container #######################################

    php-fpm:
        security_opt:
            - seccomp:unconfined
        build:
            context: ./php-fpm
            dockerfile: 7.2.dockerfile
            args:
                - USER_ID=${EUID}
        environment:
            TIMEZONE: America/Montreal
            NEW_UID: ${EUID}
        volumes_from:
            - volumes_source
        volumes:
            - ./php-fpm/php.d/:/etc/php-custom.d
            - ./logs/php:/var/log/php
        expose:
            - "9000"  
        links:
            - workspace
            - bind
            - ldap

### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

## Upgrade postgres : https://github.com/tianon/docker-postgres-upgrade
# docker run --rm \
#    -v /data/postgresql:/var/lib/postgresql/9.5/data \
#    -v /data/pgdata/9.6:/var/lib/postgresql/9.6/data \
#    tianon/postgres-upgrade:9.5-to-9.6
#
# as root: echo "host all all 0.0.0.0/0 md5" > /data/pgdata/9.6/pg_hba.conf

### PostgreSQL Container ####################################

    postgres:
        image: postgres:9.6-alpine
        volumes_from:
            - volumes_data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/pgdata

### MariaDB Container #######################################

    mariadb:
        build: ./mariadb
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### Neo4j Container #########################################

    neo4j:
        build: ./neo4j
        ports:
            - "7474:7474"
            - "1337:1337"
        environment:
            - NEO4J_AUTH=homestead:secret
        volumes_from:
            - volumes_data

### MongoDB Container #######################################

    mongo:
        build: ./mongo
        ports:
            - "27017:27017"
        volumes_from:
            - volumes_data

### Redis Container #########################################

    redis:
        image: redis:alpine
        volumes_from:
            - volumes_data
        ports:
            - "6379:6379"

### Memcached Container #####################################

    memcached:
        build: ./memcached
        volumes_from:
            - volumes_data
        ports:
            - "11211:11211"
        links:
            - php-fpm

### Beanstalkd Container ####################################

    beanstalkd:
        build: ./beanstalkd
        ports:
            - "11300:11300"
        privileged: true
        links:
            - php-fpm

### Beanstalkd Console Container ############################

    beanstalkd-console:
        build: ./beanstalkd-console
        ports:
            - "2080:2080"
        links:
            - beanstalkd

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_PRESTISSIMO=false
                - USER_ID=${EUID}
                - USER_NAME=laravel
        volumes_from:
            - volumes_source
        tty: true
        user: laravel
        links:
          - bind

### Laravel Application Code Container ######################

    volumes_source:
        build: ./volumes/application
        volumes:
            - /home/cumulus/:/var/www/laravel

### Databases Data Container ################################

    volumes_data:
        build: ./volumes/data
        volumes:
            - /data/mysql:/var/lib/mysql
            - /data/pgdata/9.6:/var/lib/pgdata
            - /data/mariadb:/var/lib/mariadb
            - /data/memcached:/var/lib/memcached
            - /data/redis:/data
            - /data/neo4j/:/var/lib/neo4j
            - /data/mongo:/var/lib/mongo
            
### Caddy Server Container ##################################
# Edit the Caddyfile if needed (./caddy/Caddyfile)

    caddy:
        build: ./caddy
        volumes_from:
            - volumes_source
        ports:
            - "80:80"
            - "443:443"
            - "2015:2015"
        volumes:
            - ./caddy/Caddyfile:/etc/Caddyfile
        links:
            - php-fpm

### Add more Containers below ###############################
    mailcatcher:
        image: belphemur/mailcatcher-exim-courrier:2.1
        environment:
            - MAILCATCHER_USERNAME=admin
            - MAILCATCHER_PASSWORD=abc123
        expose: 
            - "25"
        ports:
            - "9080:80"

    redis-commander:
          image: tenstartups/redis-commander
          command: --redis-host redis
          links:
            - redis:redis
          ports:
            - "8081:8081"
    
    bind:
          image: sameersbn/bind:latest
          ports:
            - "9088:10000"
          expose:
            - "53"
          environment:
            - ROOT_PASSWORD=abc123
          volumes:
            - /data/bind:/data
          restart: always
    ldap:
          image: osixia/openldap
          environment:
              LDAP_ADMIN_PASSWORD: abc123
          ports:
            - "389:389"
          expose:
            - "389"

    ldap-admin:
          image: osixia/phpldapadmin
          environment:
              PHPLDAPADMIN_LDAP_HOSTS: "ldap-host"
          links:
            - "ldap:ldap-host"
          ports:
            - "4443:443"
